# Generated by Django 3.1 on 2020-10-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0002_area_packlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='map_url',
        ),
        migrations.AddField(
            model_name='area',
            name='attraction_description',
            field=models.TextField(default='default value'),
        ),
        migrations.AddField(
            model_name='area',
            name='attraction_url',
            field=models.URLField(default='default value', max_length=250),
        ),
        migrations.AddField(
            model_name='area',
            name='date',
            field=models.CharField(default='default value', max_length=50),
        ),
        migrations.AddField(
            model_name='area',
            name='map',
            field=models.URLField(default='default value', max_length=250),
        ),
        migrations.AddField(
            model_name='area',
            name='place_to_stay',
            field=models.URLField(default='default value', max_length=250),
        ),
    ]
