# Generated by Django 3.1 on 2020-10-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0003_auto_20201021_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='attraction_url',
            new_name='attraction',
        ),
        migrations.AddField(
            model_name='area',
            name='restaurant',
            field=models.URLField(default='enter the link with good food', max_length=250),
        ),
    ]
