# Generated by Django 3.1 on 2020-10-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0004_auto_20201027_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='attraction_description',
            field=models.TextField(),
        ),
    ]
