# Generated by Django 3.1 on 2020-11-06 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0005_auto_20201027_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='restaurant',
        ),
        migrations.AlterField(
            model_name='area',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.URLField(max_length=250)),
                ('kind_of_food', models.CharField(blank=True, max_length=250)),
                ('name_of_restaurant', models.CharField(blank=True, max_length=250)),
                ('opening_hours', models.CharField(blank=True, max_length=250)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planer.area')),
            ],
        ),
    ]
