# Generated by Django 3.1 on 2020-11-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0006_auto_20201106_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_attraction', models.CharField(blank=True, max_length=200)),
                ('attraction_description', models.TextField()),
                ('attraction', models.URLField(default='default value', max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='area',
            name='attraction',
        ),
        migrations.RemoveField(
            model_name='area',
            name='attraction_description',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant',
        ),
    ]
