# Generated by Django 3.1 on 2020-11-09 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0007_auto_20201108_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='attraction_url',
            field=models.URLField(default='default value', max_length=250),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planer.area'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planer.area'),
        ),
    ]
