# Generated by Django 3.1 on 2020-11-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0008_auto_20201109_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='name',
            field=models.CharField(default='default value', max_length=200),
        ),
    ]
