# Generated by Django 2.2.17 on 2021-04-04 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0009_area_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='attraction',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='attraction',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planer.Area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planer.Area'),
        ),
        migrations.AlterField(
            model_name='area',
            name='map',
            field=models.URLField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='area',
            name='place_to_stay',
            field=models.URLField(default='', max_length=250),
        ),
    ]
