# Generated by Django 2.2.17 on 2021-04-05 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0010_auto_20210404_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='map',
            new_name='accommodation_link',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='date',
            new_name='date_of_arrival',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='name',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='place_to_stay',
            new_name='map_link',
        ),
        migrations.AddField(
            model_name='area',
            name='date_of_departure',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
