# Generated by Django 3.1 on 2022-01-09 17:34

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0012_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='address',
            field=django_google_maps.fields.AddressField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='area',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default='', max_length=100),
        ),
    ]
